# Generated by Django 5.1.3 on 2025-03-28 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون رقم هاتف مصري يبدأ بـ 01 ويتبعه 9 أرقام.', regex='^01[0-9]{9}$')]),
        ),
    ]
