# Generated by Django 5.1.3 on 2025-04-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rating_unique_together_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
