# Generated by Django 5.1.3 on 2025-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_bio_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.CharField(choices=[('First', 'First Year'), ('Second', 'Second Year'), ('Third', 'Third Year')], default='First', max_length=20),
            preserve_default=False,
        ),
    ]
