# Generated by Django 5.1.3 on 2025-04-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teacher_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.JSONField(default=list),
        ),
    ]
