# Generated by Django 5.1.3 on 2025-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_teacher_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='manual_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
