# Generated by Django 5.1.3 on 2025-04-25 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_teacher_manual_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='closed_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='subject',
            field=models.CharField(default='Math', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='Osama', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='Abushama', max_length=50),
            preserve_default=False,
        ),
    ]
