# Generated by Django 5.1.3 on 2025-04-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_closed_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Osama Abushama', max_length=100),
            preserve_default=False,
        ),
    ]
