# Generated by Django 5.1.3 on 2025-04-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_booking_is_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_modified',
        ),
    ]
