# Generated by Django 5.1.3 on 2025-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_booking_is_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
