# Generated by Django 5.1.3 on 2025-04-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_booking_modified_booking_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='modified_at',
        ),
    ]
