# Generated by Django 5.1.3 on 2025-04-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_booking_modified_booking_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='manual_rating',
        ),
    ]
