# Generated by Django 5.1.3 on 2025-04-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_teacher_manual_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='modified_at',
        ),
    ]
