# Generated by Django 5.1.3 on 2025-04-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_booking_modified_remove_booking_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
