# Generated by Django 5.1.3 on 2025-04-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_booking_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='place',
        ),
    ]
