# Generated by Django 5.1.3 on 2025-04-27 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_booking_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.CharField(default='sunday', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.CharField(default='ss', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('modified', 'Modified'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default='10.00', max_length=10),
            preserve_default=False,
        ),
    ]
