# Generated by Django 5.1.3 on 2025-04-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
