# Generated by Django 5.1.3 on 2025-04-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
