# Generated by Django 5.1.3 on 2025-05-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'teacher')},
        ),
    ]
