# Generated by Django 5.1.3 on 2025-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_booking_closed_time_booking_rated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
