# Generated by Django 5.1.3 on 2025-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
