# Generated by Django 5.1.3 on 2025-05-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_booking_closed_time_booking_payment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='closed_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_end_time',
        ),
    ]
