# Generated by Django 5.1.3 on 2025-05-04 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_booking_closed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 15, 19, 27, 24914, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating_prompt_shown',
            field=models.BooleanField(default=False),
        ),
    ]
