# Generated by Django 5.1.3 on 2025-05-04 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_booking_date_booking_payment_time_booking_rated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
