# Generated by Django 5.1.3 on 2025-05-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_booking_payment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rating_prompt_shown',
        ),
    ]
