# Generated by Django 5.1.3 on 2025-05-04 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_booking_date_remove_booking_payment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 23, 53, 7, 932688, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='session_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
