# Generated by Django 5.1.3 on 2025-05-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_booking_date_booking_session_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_time',
        ),
    ]
