# Generated by Django 5.1.3 on 2025-05-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_booking_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating_value',
            field=models.FloatField(default=0.0),
        ),
    ]
