# Generated by Django 5.1.3 on 2025-05-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_teacher_rating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='rating_value',
        ),
    ]
