# Generated by Django 5.1.3 on 2025-05-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_booking_closed_time_booking_rated_ratedteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
    ]
