# Generated by Django 5.1.3 on 2025-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='modified_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
