# Generated by Django 5.1.3 on 2025-05-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_booking_modified_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='modified_time',
        ),
    ]
