# Generated by Django 5.1.3 on 2025-05-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_booking_modified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_top_rated_manual',
            field=models.BooleanField(default=False),
        ),
    ]
