# Generated by Django 5.1.3 on 2025-05-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_teacher_is_top_rated_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_top_rated_manual',
        ),
    ]
