# Generated by Django 5.1.3 on 2025-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_teacher_is_top_rated_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='manually_set_top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
