# Generated by Django 5.1.3 on 2025-05-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_booking_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
