# Generated by Django 5.1.3 on 2025-05-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_booking_is_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_pending',
        ),
    ]
