# Generated by Django 5.1.3 on 2025-05-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_booking_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('modified', 'Modified'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='confirmed', max_length=20),
        ),
    ]
